### PR TITLE
Correct interface

### PR DESCRIPTION
**Pull request by odolbeau**
Looks like the Storage interface is not correct according to the PHPDoc... :(

I suggest we merge this PR & release a new major version.

WDYT @Nyholm @rvanlaak?

### CODE REVIEW

**Comment by odolbeau** [comment]
Linked to https://github.com/php-translation/symfony-bundle/issues/373

**Comment by Nyholm** [comment]
Hm. One can also see this as an opportunity to change stuff =)

When a Message is not found, should we: 
- Return null
- Throw an exception

??

**Comment by odolbeau** [comment]
I guess it's a matter of taste but I prefer the first solution: return null.

**Comment by Taluu** [comment]
Exception, as semantically speaking of something we know should exists and is not found... It should be handled through a try catch (or let it flow to the top or the relevant parts). Having to check for `null` (and throw exceptions if we want to throw one LOL) is a PITA

**Comment by lyrixx** [comment]
I agree with @odolbeau. Translation may not exist. this situation is not exceptionnnal (it's quite common to have something not translated yet in dev env)

**Review by Taluu — APPROVED** [review]

**Review by Nyholm — APPROVED** [review]

**Comment by Nyholm** [comment]
Hm. Maybe missing translations are not exceptional. And I don’t remember us throwing an exception anywhere when translations are missing. 

Thank you for the PR and the reviews.

**Pull request merged**
