### PR TITLE
Adding interface for Message

### PR DESCRIPTION
**Pull request by Nyholm**

### CODE REVIEW

**Comment by Nyholm** [comment]
This will fix #17

**Comment by rvanlaak** [comment]
Great! Code looks okay :-)

I think the only two `withXxx` methods we would need right now are the `withTranslation` and `withAddedMeta` methods though. Don't see why someone would need `withKey`, as that will also require different translations? In userland they can always use the constructor in combination with the getters.

What about renaming `withAddedMeta` to `addMeta` and `withTranslation` to `translate`, and just add a class phpdoc that tells these objects are immutable?

**Comment by rvanlaak** [comment]
Next to that I also think at least the constructor's `key` and `domain` do not need the default value. What do you think?

**Review by rvanlaak — COMMENTED** [review]
Great! Code looks okay :-)

I think the only two `withXxx` methods we would need right now are the `withTranslation` and `withAddedMeta` methods though. Don't see why someone would need `withKey`, as that will also require different translations? In userland they can always use the constructor in combination with the getters.

What about 
* renaming `withAddedMeta``  to `addMeta` and `withTranslation` to translate, and 
* just add a class phpdoc that tells these objects are immutable?

Next to that I also think at least the constructor's key and domain do not need the default value. What do you think?

**Comment by Nyholm** [comment]
Thank you for the review and Im sorry Im super late in replying. I like the pattern of using "with*" to show that it is immutable. I also make sure that the Message constructor takes at least one value

**Comment by rvanlaak** [comment]
👏

**Pull request merged**
