### PR TITLE
Prepare 4.0.0

### PR DESCRIPTION
**Pull request by odolbeau**

### CODE REVIEW

**Comment by bocharsky-bw** [comment]
Hey @odolbeau !

Thank you for creating this draft release! Do you we're ready to merge this and tag the package with v4.0.0 or do you still have any work to do on your mind before the 4.0.0 release here?

**Comment by odolbeau** [comment]
Good question, this refactoring have been put on hold since we started to work on https://github.com/symfony/symfony/pull/38475 with @welcoMattic 
I don't remember where I stopped exactly and I don't have enough time to work on this in the coming days / weeks (neither on the symfony PR unfortunately).

Maybe the work I've done here should be reverted in order to keep a clean repository? As the 4.0.0 have not been tagged yet it should be straightforward (except for crazy people using `dev-master` but they probably are aware of the risk).

What do you think?

**Comment by bocharsky-bw** [comment]
@odolbeau Ah, I see, so refactoring is blocked by symfony/symfony#38475 

> Maybe the work I've done here should be reverted in order to keep a clean repository? As the 4.0.0 have not been tagged yet it should be straightforward (except for crazy people using dev-master but they probably are aware of the risk).

I hate reverting good work, but yeah, I think it would be a very pragmatic solution here I think and it would help to achieve PHP 8 support easier.

Could you help with reverting that work? Or at least tell me what PRs should be reverted and I'd try to revert it myself

**Comment by Nyholm** [comment]
Since next release will be 4.0, I'll update branch alias in #41

**Comment by Nyholm** [comment]
Im looking at the diff. Do you mind if I release 3.1.0 before 4.0.0? 

Ie, I just revert the two BC breaking changes, then tag 3.1.0, then apply those changes again. Then we dont have to wait for next Symfony release (probably end of May).

**Comment by bocharsky-bw** [comment]
I think it would be perfect to speed up PHP 8 support

**Comment by Nyholm** [comment]
I changed my mind. It is easier to just add a single commit after 3.0.1: 
https://github.com/php-translation/common/pull/43

**Pull request closed without merging**
